# Generated by Django 4.2.9 on 2024-05-04 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2024, 5, 4, 16, 59, 33, 78189, tzinfo=datetime.timezone.utc)),
        ),
    ]
